require_relative 'spec_helper'

# require_relative '../spec/01_Basics.rb'
# require_relative '../spec/02_BeginningToEnd.rb'
# require_relative '../spec/03_Or.rb'
# require_relative '../spec/04_CharacterSets.rb'
# require_relative '../spec/05_CharacterSetShortcuts.rb'
# require_relative '../spec/06_Modifiers.rb'
# require_relative '../spec/07_RepeatingCharacters.rb'
# require_relative '../spec/08_GreedyVsMinimal.rb'
# require_relative '../spec/09_Grouping.rb'
# require_relative '../spec/10_CapturingGroups.rb'
# require_relative '../spec/11_Intermission.rb'
# require_relative '../spec/12_RegexReplace.rb'
# require_relative '../spec/13_LookingAhead.rb'